### ISSUE TITLE
Trailing Comma.

### ISSUE THREAD

**Issue by ahmgeek** [erikdahlstrand/shrine-rails-example#10]
[Regard this line](https://github.com/erikdahlstrand/shrine-rails-example/blob/master/config/initializers/shrine.rb#L13)
why this comma - at the end of that line - specifically putted there ? is it some convention ?

**Comment by janko-m** [comment]
There are two main reasons for having a comma after the last element of a collection. First one is that when adding/removing elements at the end of the array, you don't have to have the mental overhead of remembering to add/remove trailing commas. This happens to me so often:

```rb
[
  "one",
  "two",
  "three" # this was the last item
  "new"   # this was new item, but I forgot to put a comma on "three", so I get a syntax error
]
```

The second reason is prettier Git diffs. Let me demonstrate this on a recent example I had when writing my new [blog post](http://twin.github.io/activerecord-is-reinventing-sequel/), where I wanted to find out when JSON support was added to ActiveRecord. I encountered this code:

```rb
NATIVE_DATABASE_TYPES = {
  # ...
  tsvector:    { name: "tsvector" },
  hstore:      { name: "hstore" },
  inet:        { name: "inet" },
  cidr:        { name: "cidr" },
  macaddr:     { name: "macaddr" },
  uuid:        { name: "uuid" },
  json:        { name: "json" }, # <==== here it is
  jsonb:       { name: "jsonb" },
  ltree:       { name: "ltree" },
  citext:      { name: "citext" },
  point:       { name: "point" },
  line:        { name: "line" },
  lseg:        { name: "lseg" },
  box:         { name: "box" },
# ...
}
```

Ok, let's `git blame` the line where the "json" key appears:

```diff
@@ -329,7 +339,8 @@ module ActiveRecord
         cidr:        { name: "cidr" },
         macaddr:     { name: "macaddr" },
         uuid:        { name: "uuid" },
-        json:        { name: "json" }
+        json:        { name: "json" },
+        intrange:    { name: "int4range" }
       }
 
       include Quoting
```

Aha, this commit isn't related to the "json" key-value pair, it only adds a trailing comma because "intrange" is being added at the end. Ok, let's `git blame` again when "json" was the last element:

```diff
@@ -290,7 +300,8 @@ module ActiveRecord
         inet:        { name: "inet" },
         cidr:        { name: "cidr" },
         macaddr:     { name: "macaddr" },
-        uuid:        { name: "uuid" }
+        uuid:        { name: "uuid" },
+        json:        { name: "json" }
       }
 
       include Quoting
```

Ok, the "uuid" line changing is a bit confusing, but we see that this is where the "json" line was added, so this is the right commit.

I think not adding a trailing comma to the last item of the list creates unnecessary mental overhead. And it makes sense in general, because by adding a trailing comma you make the last item the same as the previous ones, because it's not any different than others, it only happens to be at the end of the list.

Note that questions like this are best asked by email, or the Shrine Google group if it's Shrine-related. GitHub issues should be used only for bugs :)

**Comment by ahmgeek** [comment]
TIL: that you're awesome :heart:
you taught me new something today, thanks :kiss: 

About the note, I know that github issues is for bugs, but sometimes I doubt any replies for my question in mails/groups. that's why I ask it in an issue, but next time will make sure to ask in G groups or by mail.
thanks man.
P.S: check your gmail :smile:, to be specific, filter it to that date: 9/14/2015.
