### ISSUE TITLE
Adding a default image

### ISSUE THREAD

**Issue by flyingboy007** [erikdahlstrand/shrine-rails-example#11]
Is it possible to add a default_url when s3 is not reachable?

**Comment by janko-m** [comment]
This is not something that can be done by server side in a sane way, because you would have to make a request to each URL to check if the service is down. It makes much more sense to do this with JavaScript: http://stackoverflow.com/a/92819

As mentioned previously, usage questions are best asked at the [Google group](https://groups.google.com/forum/#!forum/ruby-shrine), GitHub issues should only be used for bug reports.

**Comment by flyingboy007** [comment]
Will keep that in mind.Thanks mate.
