### ISSUE TITLE
POST error

### ISSUE THREAD

**Issue by pmackay** [erikdahlstrand/shrine-rails-example#12]
I can get this example app to work, and am trying to set a similar file upload up in another app. I'm getting a `400 Bad Request` with this response. 

```
<Error>
<Code>InvalidArgument</Code>
<Message>Malformed Unicode code sequence in the field.</Message>
<ArgumentName>formField</ArgumentName>
<RequestId>6D3FCAB1348B56CB</RequestId>
<HostId>LzZXcHD2st8YRUBpw6qptqRCRQ4Pj6QKMT1+as6zdvmyL8l/mAEt6xvxknhvnomb26aum/mdGzs=</HostId>
</Error>
```
Any suggestions on what might be triggering this Malformed Unicode message? Thanks!

**Comment by janko-m** [comment]
Hmm, I don't know what might be the error. You can check the Network tab in your browser, and see the request body to check if everything looks in order. Or maybe better just `console.log()` the parameters that you're giving to the AJAX call. The fields that are sent to AWS S3 are typically

```rb
{
  "url" => "https://my-bucket.s3-eu-west-1.amazonaws.com",
  "fields" => {
    "key" => "...",
    "policy" => "...",
    "x-amz-credential" => "...",
    "x-amz-algorithm" => "...",
    "x-amz-date" => "...",
    "x-amz-signature" => "..."
  }
}
```

So it's strange that you're getting an error on a "formField" argument. Check if it's even sent, then maybe you should remove any non-ASCII characters there, I don't know.

I will close this, because communication and setup of Amazon S3 is unrelated to Shrine, Shrine only gives presign parameters, of which a "formField" isn't a member.
