### ISSUE TITLE
Update it please it not working properly and make it some better example thanks 

### ISSUE THREAD

**Issue by saroar** [erikdahlstrand/shrine-rails-example#13]

**Comment by janko-m** [comment]
@saroar Can you tell me what is not working properly?

**Comment by saroar** [comment]
i delete app after not working i dont wanted to lose my time but i remember after upload file from my local disk it was not upload for long time then if u click save it was give some error 
thats all i remember

**Comment by janko-m** [comment]
@saroar Unfortunately, that's not enough information. The file upload might have been taking a long time because of slow internet. However, uploading to S3 is the point of this example app, to show how to setup a complex real-world scenario (multiple direct uploads to S3 with backgrounding) with Shrine. So I would rather fix any bugs in this app than create a new one.
