### ISSUE TITLE
Is there any particular reason on moving to suckerpunch from sidekiq??

### ISSUE THREAD

**Issue by flyingboy007** [erikdahlstrand/shrine-rails-example#7]
I was just wondering Is there any particular reason on moving to `suckerpunch` from `sidekiq` which was on the previous one?  

By the way good to see the progress bar implemented in example app.

**Comment by janko-m** [comment]
Because then everything runs in the same process (so your logs are at one place), and Redis is not required. I remember that for some reason in development Sidekiq was sometimes not picking up a new jobs, and I never really solved it. I would definitely use Sidekiq for serious apps, but for demonstration purposes SuckerPunch is simpler.
